-- 1
DROP TABLE IF EXISTS students CASCADE;
-- 2
DROP TABLE IF EXISTS employees CASCADE;
-- 3
DROP TABLE IF EXISTS authors CASCADE;
-- 4
DROP TABLE IF EXISTS books CASCADE;
-- 5
DROP TABLE IF EXISTS rentals CASCADE;
-- 6
DROP TABLE IF EXISTS completion_date CASCADE;
--7
DROP TABLE IF EXISTS quantity_books CASCADE;
--8
DROP TABLE IF EXISTS supply_history CASCADE;